# Generated by Django 5.0.6 on 2024-09-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_employee_email_employee_pwd_alter_employee_join_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
