# Generated by Django 5.1.4 on 2025-01-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0006_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
