# Generated by Django 5.1.4 on 2025-03-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0008_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
