# Generated by Django 5.1.4 on 2025-03-26 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0009_employee_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_PG', models.CharField(max_length=100, null=True)),
                ('clg_name_PG', models.CharField(max_length=200, null=True)),
                ('year_of_pass_PG', models.CharField(max_length=50, null=True)),
                ('percentage_PG', models.CharField(max_length=50, null=True)),
                ('course_Grad', models.CharField(max_length=100, null=True)),
                ('clg_name_Grad', models.CharField(max_length=200, null=True)),
                ('year_of_pass_Grad', models.CharField(max_length=50, null=True)),
                ('percentage_Grad', models.CharField(max_length=50, null=True)),
                ('course_HSC', models.CharField(max_length=100, null=True)),
                ('clg_name_HSC', models.CharField(max_length=200, null=True)),
                ('year_of_pass_HSC', models.CharField(max_length=50, null=True)),
                ('percentage_HSC', models.CharField(max_length=50, null=True)),
                ('course_SSC', models.CharField(max_length=100, null=True)),
                ('clg_name_SSC', models.CharField(max_length=200, null=True)),
                ('year_of_pass_SSC', models.CharField(max_length=50, null=True)),
                ('percentage_SSC', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name1', models.CharField(max_length=100, null=True)),
                ('Possition1', models.CharField(max_length=100, null=True)),
                ('salary1', models.CharField(max_length=100, null=True)),
                ('Duration1', models.CharField(max_length=100, null=True)),
                ('Company_name2', models.CharField(max_length=100, null=True)),
                ('Possition2', models.CharField(max_length=100, null=True)),
                ('salary2', models.CharField(max_length=100, null=True)),
                ('Duration2', models.CharField(max_length=100, null=True)),
                ('Company_name3', models.CharField(max_length=100, null=True)),
                ('Possition3', models.CharField(max_length=100, null=True)),
                ('salary3', models.CharField(max_length=100, null=True)),
                ('Duration3', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
